web: apache2-foreground
horizon: php artisan horizon
release: bash -c "php artisan storage:link; php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache"
