<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('execution_checkpoints', function (Blueprint $table) {
            // UUID generated by WaitNode(webhook mode) — used to look up the
            // checkpoint when the external webhook arrives at /webhook-wait/{uuid}.
            $table->uuid('webhook_wait_uuid')
                ->nullable()
                ->unique()
                ->after('suspend_reason');

            // Payload that arrived at /webhook-wait/{uuid}, injected as the
            // WaitNode's output so downstream nodes can read it.
            $table->json('resume_payload')
                ->nullable()
                ->after('webhook_wait_uuid');
        });
    }

    public function down(): void
    {
        Schema::table('execution_checkpoints', function (Blueprint $table) {
            $table->dropColumn(['webhook_wait_uuid', 'resume_payload']);
        });
    }
};
